add_newline = false

[battery]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[git_branch]
symbol = ""

[golang]
symbol = "go: "

[ruby]
symbol = "rb: "

[rust]
symbol = "rs: "

[nodejs]
format = "node: "
detect_files = ['package.json', '.node-version', '!bunfig.toml', '!bun.lockb']

[bun]
symbol = "bun: "
